export const TOGGLE_EXPAND_MENU_ITEM = 'TOGGLE_EXPAND_MENU_ITEM';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';

export const TOGGLE_WITHOUT_ANIMATION = 'TOGGLE_WITHOUT_ANIMATION';

export const MOVE_TO_TRASH_ITEMS_SUCCESS = "MOVE_TO_TRASH_ITEMS_SUCCESS";

export const MOVE_TO_TRASH_ITEMS_FAILED = "MOVE_TO_TRASH_ITEMS_FAILED";

export const DELETE_ITEMS_SUCCESS = "DELETE_ITEMS_SUCCESS";

export const DELETE_ITEMS_FAILED = "DELETE_ITEMS_FAILED";

export const GOTO = "GOTO";

export const GOTO_DETAIL = "GOTO_DETAIL";

export const GOTO_LIST = "GOTO_LIST";

export const PUBLISH_ITEMS_SUCCESS = "PUBLISH_ITEMS_SUCCESS";

export const PUBLISH_ITEMS_FAILED = "PUBLISH_ITEMS_FAILED";

export const UNPUBLISH_ITEMS_SUCCESS = "UNPUBLISH_ITEMS_SUCCESS";

export const UNPUBLISH_ITEMS_FAILED = "UNPUBLISH_ITEMS_FAILED";

export const SAVE_ITEM_SUCCESS = "SAVE_ITEM_SUCCESS";

export const SAVE_ITEM_FAILED = "SAVE_ITEM_FAILED";

export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";

export const GET_ITEM_FAILED = "GET_ITEM_FAILED";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";

export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";

export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";

export const GET_DATA_FAILED = "GET_DATA_FAILED";

export const UPDATE_AUTH = "UPDATE_AUTH";

export const SUCCESS = "SUCCESS";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const GET_USERS_FAILED = "GET_USERS_FAILED";

export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";

export const SEND_EMAIL_FAILED = "SEND_EMAIL_FAILED";